### ISSUE TITLE
Update Docker section reflecting Docker Desktop licence change

### ISSUE THREAD

**Issue by mkrg-capco** [capcodigital/team-course#17]
Since the Docker Desktop licence has changed ([grace period ends on 31st of Jan 2022](https://docs.docker.com/desktop/windows/install/)) we should reflect it in [Docker](https://github.com/capcodigital/team-course/blob/master/documentation/java/Docker.md) section of the course.

The alternative to Capco paying for licences for each user is to use still free alternative, such as:

- [Rancher Desktop](https://rancherdesktop.io)
- [Podman](https://podman.io/getting-started/)

**Comment by jfnw-capco** [comment]
With the pending rollout of Docker Business licenses within Capco this issue is now not needed.
